import { LanguageProvider } from '@inlang/paraglide-next';
import { languageTag } from '@/paraglide/runtime.js';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '../components/header/header';
import { cn } from '@/lib/utils';
import TransactionContextProvider from '../context/transactionContext';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<LanguageProvider>
			<TransactionContextProvider>
				<html lang={languageTag()}>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          </head>
					<body
						className={cn(
							`${geistSans.variable} ${geistMono.variable} antialiased`,
							'bg-white text-defaultBlack font-sans text-medium leading-medium'
						)}
					>
						<div className="md:px-10 px-3 w-full">
							<Header />
							<div className="mx-auto md:max-w-6xl">{children}</div>
						</div>
					</body>
				</html>
			</TransactionContextProvider>
		</LanguageProvider>
	);
}
